# Generated by Django 5.1.1 on 2024-09-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customar',
            name='customar_type',
        ),
        migrations.AddField(
            model_name='customar',
            name='customer_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Non-Regular', 'Non-Regular')], default='Non-Regular', max_length=20),
        ),
        migrations.DeleteModel(
            name='Customar_type',
        ),
    ]
