# Generated by Django 5.1.1 on 2024-09-14 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_customar_ditail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customar_ditail',
            name='customer',
        ),
        migrations.DeleteModel(
            name='customar',
        ),
        migrations.DeleteModel(
            name='customar_ditail',
        ),
    ]
