# Generated by Django 5.1.1 on 2024-09-14 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0004_remove_customar_ditail_customer_delete_customar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='customar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('Regular', 'Regular'), ('Non-Regular', 'Non-Regular')], default='Non-Regular', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=1000)),
                ('fhone', models.IntegerField(max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='customar_ditail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_product', models.TextField(max_length=1000)),
                ('given_money', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=10, default=0, max_digits=100)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('pay_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.customar')),
            ],
        ),
    ]
