# Generated by Django 5.1.1 on 2024-09-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customar',
            name='fhone',
            field=models.CharField(max_length=15),
        ),
    ]
