# Generated by Django 5.1.1 on 2024-09-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_alter_customar_fhone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customar_ditail',
            name='get_money',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
