# Generated by Django 5.1.1 on 2024-09-16 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_customar_ditail_get_money'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='total_cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_rent', models.IntegerField(blank=True)),
                ('bill', models.IntegerField(blank=True)),
                ('employs_sallary', models.IntegerField(blank=True)),
                ('buy_product_list', models.TextField(blank=True, max_length=10000)),
                ('by_product_rate', models.IntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
