# Generated by Django 5.1.1 on 2024-09-17 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_total_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='owed_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owed_money_for_product', models.CharField(max_length=200000)),
                ('owed_money', models.IntegerField()),
                ('owed_customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.customar')),
            ],
        ),
    ]
