# Generated by Django 5.1.1 on 2024-09-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_owed_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total_cost',
            name='bill',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total_cost',
            name='buy_product_list',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='total_cost',
            name='by_product_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total_cost',
            name='employs_sallary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total_cost',
            name='store_rent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
