# Generated by Django 5.1.1 on 2024-09-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_owed_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='owed_detail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
