# Generated by Django 5.1.1 on 2024-09-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_alter_total_cost_bill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total_cost',
            name='bill',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='total_cost',
            name='by_product_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='total_cost',
            name='employs_sallary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='total_cost',
            name='store_rent',
            field=models.IntegerField(default=0),
        ),
    ]
