# Generated by Django 5.1.1 on 2024-09-17 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_owed_detail_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='owed_detail',
        ),
    ]
