# Generated by Django 5.1.1 on 2024-09-21 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_total_cost_name_mounth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='owed_detail',
        ),
    ]
