# Generated by Django 5.1.1 on 2024-09-23 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_owed_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='owed_detail',
        ),
    ]
