# Generated by Django 5.1.1 on 2024-09-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0018_profit_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit_detail',
            name='extra',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
    ]
