# Generated by Django 5.1.1 on 2024-09-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_alter_profit_detail_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit_detail',
            name='extra_profit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
